#!/bin/bash
echo"STEP1:Update the ubuntu and install the 'zip' and 'openjdk-17'"
sudo apt update -y && sudo apt install -y zip openjdk-17-jdk

echo"STEP2:Download apache-maven-3.9.6.zip and unzip it"
wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip && unzip apache-maven-3.9.6-bin.zip

echo"Create a symbolic link of mvn binary in $PATH (load the maven command"
sudo ln -s /home/ubuntu/apache-maven-3.9.6/bin/mvn /usr/local/sbin/mvn

echo"Giving full permission"
sudo chmod 777 /usr/local/sbin/mvn

echo"------jdk and maven installed------------"
