#!/bin/bash

echo"STEP1: "Update the ubuntu and insatall java jdk-17"
sudo apt update && sudo apt install -y openjdk-17-jdk

echo"STEP2: "'jenkins' installation pre-process"
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]" \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

echo"STEP3: Update the ubuntu"
sudo apt-get update

echo"STEP4: jenkins' installation"
sudo apt-get install jenkins

