#!/bin/bash

echo"STEP1: Update the ubuntu and insatall java jdk-17"
sudo apt update && sudo apt install -y openjdk-17-jdk

echo"STEP2: Create a directory 'jenkins' and give full permission"
mkdir jenkins && sudo chmod 777 jenkins

echo"Update the ubuntu"
sudo apt update
